services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
  dummy-server:
    build: dummy-server/
    ports:
      - "3000:3000"
    volumes:
      - ./dummy-server/data:/data
